version: "3.8"

services:
  flask-1:
    image: flask_demo
    ports:
      - "4400:4000"

  flask-2:
    image: flask_demo
    ports:
      - "8800:4000"

  flask-3:
    image: flask_demo
    ports:
      - "8888:4000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/etc/nginx/html/index.html
    ports:
      - 8881:8881
      - 8801:8801
      - 4401:4401
